import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/header/Header";
import styles from "../styles/Home.module.css";
import "antd/dist/antd.css";
import Section1 from "../components/section1/Section1";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Stylique Internship</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div style={{width: '100%'  , display: 'flex' , justifyContent: 'center' ,}}>
      <div style={{width: '90%',  borderLeft: '1px solid grey'}}> */}
        <Header />
        <Section1 />
      {/* </div>
      </div> */}
    </div>
  );
};

export default Home;
