import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/header/Header";
import styles from "../styles/Home.module.css";
import "antd/dist/antd.css";
import Section1 from "../components/section1/Section1";
import Section2 from "../components/section2/Section2";


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Stylique Internship</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header />
        <Section1 />
        <Section2 />
    </div>
  );
};

export default Home;
